### ISSUE TITLE
undefined method `children' for nil:NilClass

### ISSUE THREAD

**Issue by chrise86** [Nedomas/zapata#11]
Not really sure what's causing this one, any ideas? Stack trace below:

```
/Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/unparser-0.1.16/lib/unparser/emitter.rb:298:in `children': undefined method `children' for nil:NilClass (NoMethodError)
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/unparser-0.1.16/lib/unparser/emitter/literal/hash.rb:99:in `effective_body'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/unparser-0.1.16/lib/unparser/emitter/literal/hash.rb:89:in `dispatch'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/unparser-0.1.16/lib/unparser/emitter.rb:103:in `write_to_buffer'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:117:in `call'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:117:in `block (3 levels) in create_memoized_method'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/memoizable-0.4.2/lib/memoizable/memory.rb:63:in `block (3 levels) in fetch'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/thread_safe-0.3.5/lib/thread_safe/cache.rb:58:in `fetch'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/memoizable-0.4.2/lib/memoizable/memory.rb:62:in `block (2 levels) in fetch'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/memoizable-0.4.2/lib/memoizable/memory.rb:61:in `block in fetch'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/thread_safe-0.3.5/lib/thread_safe/cache.rb:58:in `fetch'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/memoizable-0.4.2/lib/memoizable/memory.rb:60:in `fetch'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:116:in `block (2 levels) in create_memoized_method'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/unparser-0.1.16/lib/unparser/emitter.rb:498:in `run'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/unparser-0.1.16/lib/unparser/emitter/literal/hash.rb:149:in `block in emit_hash_body'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/unparser-0.1.16/lib/unparser/emitter.rb:184:in `parentheses'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/unparser-0.1.16/lib/unparser/emitter/literal/hash.rb:147:in `emit_hash_body'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/unparser-0.1.16/lib/unparser/emitter/literal/hash.rb:136:in `dispatch'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/unparser-0.1.16/lib/unparser/emitter.rb:103:in `write_to_buffer'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:117:in `call'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:117:in `block (3 levels) in create_memoized_method'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/memoizable-0.4.2/lib/memoizable/memory.rb:63:in `block (3 levels) in fetch'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/thread_safe-0.3.5/lib/thread_safe/cache.rb:58:in `fetch'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/memoizable-0.4.2/lib/memoizable/memory.rb:62:in `block (2 levels) in fetch'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/memoizable-0.4.2/lib/memoizable/memory.rb:61:in `block in fetch'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/thread_safe-0.3.5/lib/thread_safe/cache.rb:58:in `fetch'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/memoizable-0.4.2/lib/memoizable/memory.rb:60:in `fetch'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:116:in `block (2 levels) in create_memoized_method'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/unparser-0.1.16/lib/unparser/emitter.rb:212:in `block in visit'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/unparser-0.1.16/lib/unparser/emitter.rb:242:in `conditional_parentheses'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/unparser-0.1.16/lib/unparser/emitter.rb:211:in `visit'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/unparser-0.1.16/lib/unparser/emitter/literal/hash.rb:23:in `block in emit_value'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/unparser-0.1.16/lib/unparser/emitter.rb:242:in `conditional_parentheses'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/unparser-0.1.16/lib/unparser/emitter/literal/hash.rb:22:in `emit_value'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/unparser-0.1.16/lib/unparser/emitter/literal/hash.rb:65:in `dispatch'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/unparser-0.1.16/lib/unparser/emitter.rb:103:in `write_to_buffer'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:117:in `call'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:117:in `block (3 levels) in create_memoized_method'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/memoizable-0.4.2/lib/memoizable/memory.rb:63:in `block (3 levels) in fetch'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/thread_safe-0.3.5/lib/thread_safe/cache.rb:58:in `fetch'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/memoizable-0.4.2/lib/memoizable/memory.rb:62:in `block (2 levels) in fetch'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/memoizable-0.4.2/lib/memoizable/memory.rb:61:in `block in fetch'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/thread_safe-0.3.5/lib/thread_safe/cache.rb:58:in `fetch'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/memoizable-0.4.2/lib/memoizable/memory.rb:60:in `fetch'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:116:in `block (2 levels) in create_memoized_method'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/unparser-0.1.16/lib/unparser/emitter.rb:212:in `block in visit'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/unparser-0.1.16/lib/unparser/emitter.rb:242:in `conditional_parentheses'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/unparser-0.1.16/lib/unparser/emitter.rb:211:in `visit'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/unparser-0.1.16/lib/unparser/emitter.rb:284:in `call'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/unparser-0.1.16/lib/unparser/emitter.rb:284:in `delimited'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/unparser-0.1.16/lib/unparser/emitter/literal/hash.rb:89:in `dispatch'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/unparser-0.1.16/lib/unparser/emitter.rb:103:in `write_to_buffer'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:117:in `call'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:117:in `block (3 levels) in create_memoized_method'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/memoizable-0.4.2/lib/memoizable/memory.rb:63:in `block (3 levels) in fetch'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/thread_safe-0.3.5/lib/thread_safe/cache.rb:58:in `fetch'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/memoizable-0.4.2/lib/memoizable/memory.rb:62:in `block (2 levels) in fetch'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/memoizable-0.4.2/lib/memoizable/memory.rb:61:in `block in fetch'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/thread_safe-0.3.5/lib/thread_safe/cache.rb:58:in `fetch'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/memoizable-0.4.2/lib/memoizable/memory.rb:60:in `fetch'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:116:in `block (2 levels) in create_memoized_method'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/unparser-0.1.16/lib/unparser/emitter.rb:198:in `visit_plain'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/unparser-0.1.16/lib/unparser/emitter.rb:287:in `call'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/unparser-0.1.16/lib/unparser/emitter.rb:287:in `block in delimited'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/unparser-0.1.16/lib/unparser/emitter.rb:285:in `each'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/unparser-0.1.16/lib/unparser/emitter.rb:285:in `delimited'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/unparser-0.1.16/lib/unparser/emitter.rb:268:in `delimited_plain'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/unparser-0.1.16/lib/unparser/emitter/send/arguments.rb:21:in `block in dispatch'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/unparser-0.1.16/lib/unparser/emitter.rb:184:in `parentheses'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/unparser-0.1.16/lib/unparser/emitter/send/arguments.rb:20:in `dispatch'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/unparser-0.1.16/lib/unparser/emitter.rb:103:in `write_to_buffer'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:117:in `call'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:117:in `block (3 levels) in create_memoized_method'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/memoizable-0.4.2/lib/memoizable/memory.rb:63:in `block (3 levels) in fetch'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/thread_safe-0.3.5/lib/thread_safe/cache.rb:58:in `fetch'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/memoizable-0.4.2/lib/memoizable/memory.rb:62:in `block (2 levels) in fetch'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/memoizable-0.4.2/lib/memoizable/memory.rb:61:in `block in fetch'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/thread_safe-0.3.5/lib/thread_safe/cache.rb:58:in `fetch'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/memoizable-0.4.2/lib/memoizable/memory.rb:60:in `fetch'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:116:in `block (2 levels) in create_memoized_method'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/unparser-0.1.16/lib/unparser/emitter.rb:498:in `run'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/unparser-0.1.16/lib/unparser/emitter/send.rb:187:in `emit_arguments'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/unparser-0.1.16/lib/unparser/emitter/send/regular.rb:21:in `dispatch'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/unparser-0.1.16/lib/unparser/emitter.rb:103:in `write_to_buffer'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:117:in `call'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:117:in `block (3 levels) in create_memoized_method'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/memoizable-0.4.2/lib/memoizable/memory.rb:63:in `block (3 levels) in fetch'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/thread_safe-0.3.5/lib/thread_safe/cache.rb:58:in `fetch'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/memoizable-0.4.2/lib/memoizable/memory.rb:62:in `block (2 levels) in fetch'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/memoizable-0.4.2/lib/memoizable/memory.rb:61:in `block in fetch'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/thread_safe-0.3.5/lib/thread_safe/cache.rb:58:in `fetch'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/memoizable-0.4.2/lib/memoizable/memory.rb:60:in `fetch'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:116:in `block (2 levels) in create_memoized_method'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/unparser-0.1.16/lib/unparser/emitter/send.rb:32:in `dispatch'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/unparser-0.1.16/lib/unparser/emitter.rb:103:in `write_to_buffer'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:117:in `call'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:117:in `block (3 levels) in create_memoized_method'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/memoizable-0.4.2/lib/memoizable/memory.rb:63:in `block (3 levels) in fetch'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/thread_safe-0.3.5/lib/thread_safe/cache.rb:58:in `fetch'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/memoizable-0.4.2/lib/memoizable/memory.rb:62:in `block (2 levels) in fetch'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/memoizable-0.4.2/lib/memoizable/memory.rb:61:in `block in fetch'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/thread_safe-0.3.5/lib/thread_safe/cache.rb:58:in `fetch'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/memoizable-0.4.2/lib/memoizable/memory.rb:60:in `fetch'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:116:in `block (2 levels) in create_memoized_method'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/unparser-0.1.16/lib/unparser.rb:31:in `unparse'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/zapata-0.1.5/lib/zapata/primitive/send.rb:36:in `to_raw'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/zapata-0.1.5/lib/zapata/primitive/arg.rb:11:in `to_raw'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/zapata-0.1.5/lib/zapata/primitive/array.rb:17:in `block in to_raw'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/zapata-0.1.5/lib/zapata/primitive/array.rb:15:in `map'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/zapata-0.1.5/lib/zapata/primitive/array.rb:15:in `to_raw'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/zapata-0.1.5/lib/zapata/predictor/args.rb:8:in `literal'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/zapata-0.1.5/lib/zapata/primitive/def.rb:29:in `literal_predicted_args'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/zapata-0.1.5/lib/zapata/rzpec/writer.rb:100:in `write_method'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/zapata-0.1.5/lib/zapata/rzpec/writer.rb:55:in `block in write_class'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/zapata-0.1.5/lib/zapata/rzpec/writer.rb:54:in `each'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/zapata-0.1.5/lib/zapata/rzpec/writer.rb:54:in `write_class'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/zapata-0.1.5/lib/zapata/rzpec/writer.rb:23:in `block in initialize'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/zapata-0.1.5/lib/zapata/rzpec/writer.rb:22:in `each'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/zapata-0.1.5/lib/zapata/rzpec/writer.rb:22:in `initialize'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/zapata-0.1.5/lib/zapata.rb:84:in `new'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/zapata-0.1.5/lib/zapata.rb:84:in `generate_rspec_for'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/zapata-0.1.5/lib/zapata.rb:36:in `generate'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/zapata-0.1.5/lib/zapata.rb:28:in `generate_with_friendly_output'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/zapata-0.1.5/bin/zapata:20:in `block (3 levels) in <top (required)>'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/slop-3.6.0/lib/slop.rb:260:in `call'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/slop-3.6.0/lib/slop.rb:260:in `parse!'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/slop-3.6.0/lib/slop.rb:235:in `parse!'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/slop-3.6.0/lib/slop.rb:211:in `parse'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/zapata-0.1.5/bin/zapata:32:in `<top (required)>'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/bin/zapata:23:in `load'
	from /Users/chrisedwards/.rbenv/versions/2.2.1/bin/zapata:23:in `<main>'
```

**Comment by Nedomas** [comment]
Hello, Chris and thanks a lot for reporting it. :heart:

Could there be a mistype somewhere?
Zapata tries to output that this variable is missing, but crasher while trying to parse your ruby code.

https://github.com/Nedomas/zapata/blob/master/lib/zapata/primitive/send.rb#L36

Could you try to rescue this and print the code it tries to "unparse"?

**Comment by Nedomas** [comment]
Reopen if still an issue.
