### ISSUE TITLE
Whenever I try to create a test I get errors with unparser

### ISSUE THREAD

**Issue by askl56** [Nedomas/zapata#12]
```
[andrew@mbp ~/code/blocitoff (master *)]$ zapata generate app/models/user.rb 
warning: you are loading parser/ruby22 from /Users/andrew/.rvm/gems/ruby-2.2.0/gems/parser-2.2.0.pre.8/lib/parser/current.rb:40:in `require'.
warning: Ruby 2.2 is not released yet and parser support may be incomplete.
/Users/andrew/.rvm/gems/ruby-2.2.0/gems/unparser-0.1.16/lib/unparser/emitter.rb:449: warning: circular argument reference - body
/Users/andrew/.rvm/gems/ruby-2.2.0/gems/unparser-0.1.16/lib/unparser/emitter.rb:497: warning: circular argument reference - node
[1/3] Analyzing: app/models/todo_item.rb
[2/3] Analyzing: app/models/todo_list.rb
[3/3] Analyzing: app/models/user.rb
Its done, comrades. File spec/models/user_spec.rb was generated.
[andrew@mbp ~/code/blocitoff (master *)]$ rspec spec/models/user_spec.rb 
warning: you are loading parser/ruby22 from /Users/andrew/.rvm/gems/ruby-2.2.0/gems/parser-2.2.0.pre.8/lib/parser/current.rb:40:in `require'.
warning: Ruby 2.2 is not released yet and parser support may be incomplete.
/Users/andrew/.rvm/gems/ruby-2.2.0/gems/unparser-0.1.16/lib/unparser/emitter.rb:449: warning: circular argument reference - body
/Users/andrew/.rvm/gems/ruby-2.2.0/gems/unparser-0.1.16/lib/unparser/emitter.rb:497: warning: circular argument reference - node
No examples found.

```

**Comment by Nedomas** [comment]
Whatsup, Andrew.

Thanks for reporting and sorry for the bugs :sake: 

Does it create an empty file? I checked out your user.rb (https://github.com/askl56/bloccit/blob/master/app/models/user.rb) and Zapata should be able to parse it.

The unparser **warnings** are there just because we have warnings mode turned on somewhere. That is helpful for debugging but should be disabled on a released gem.

I had updated ``parser`` earlier to prerelease version ``2.2.0.pre.8`` because of do block bug we had (https://github.com/Nedomas/zapata/commit/ee20fff127be35a35189d0d83dc948aae4accba8).

Could you try updating the ``parser`` to ``2.2.0.3`` ?

P.S. Thanks for looking into it :+1:

**Comment by askl56** [comment]
Hi Nedomas. When I update the parser I get

```
[andrew@mbp ~/code/blocitoff (master *)]$ gem install parser 2.2.0.3
Fetching: parser-2.2.0.3.gem (100%)
Successfully installed parser-2.2.0.3
Parsing documentation for parser-2.2.0.3
Installing ri documentation for parser-2.2.0.3
Done installing documentation for parser after 10 seconds
ERROR:  Could not find a valid gem '2.2.0.3' (>= 0) in any repository
1 gem installed
```

**Comment by askl56** [comment]
And I still get

```
[andrew@mbp ~/code/blocitoff (master *)]$ rake db:migrate
warning: you are loading parser/ruby22 from /Users/andrew/.rvm/gems/ruby-2.2.0/gems/parser-2.2.0.pre.8/lib/parser/current.rb:40:in `require'.
warning: Ruby 2.2 is not released yet and parser support may be incomplete.
/Users/andrew/.rvm/gems/ruby-2.2.0/gems/unparser-0.1.16/lib/unparser/emitter.rb:449: warning: circular argument reference - body
/Users/andrew/.rvm/gems/ruby-2.2.0/gems/unparser-0.1.16/lib/unparser/emitter.rb:497: warning: circular argument reference - node
```

**Comment by askl56** [comment]
Any further joy with this?

**Comment by Nedomas** [comment]
Sorry for such a delay. I moved companies and just started using ``Rspec`` and ``zapata`` once again.

I expect to find the time over the next week to look into it as generate more stuff for us. Thanks for being zen about it and sorry for the corporate release cycles! :hear_no_evil:

**Comment by askl56** [comment]
Let me know if you need help as far as collaboration goes.

**Comment by askl56** [comment]
Any joy?

**Comment by askl56** [comment]
Are you planning on updating the gem?

**Comment by askl56** [comment]
I have solved this issue for myself.
