### ISSUE TITLE
`choose_values': Not yet implemented 

### ISSUE THREAD

**Issue by skatkov** [Nedomas/zapata#13]
Good day, i've received big project with small test coverage. Trying to save a day with zapata (first time).

After digging through some issue, i ended up with an issue that comes from zapata and I don't really know how to fix it. 

After analyzing my models it shows me this error:
```ruby
/Users/lun/.rvm/gems/ruby-2.0.0-p643/gems/zapata-0.1.5/lib/zapata/predictor/args.rb:36:in `choose_values': Not yet implemented (RuntimeError)
        from /Users/lun/.rvm/gems/ruby-2.0.0-p643/gems/zapata-0.1.5/lib/zapata/predictor/args.rb:9:in `literal'
        from /Users/lun/.rvm/gems/ruby-2.0.0-p643/gems/zapata-0.1.5/lib/zapata/primitive/const_send.rb:15:in `to_raw'
        from /Users/lun/.rvm/gems/ruby-2.0.0-p643/gems/zapata-0.1.5/lib/zapata/primitive/send.rb:33:in `to_raw'
        from /Users/lun/.rvm/gems/ruby-2.0.0-p643/gems/zapata-0.1.5/lib/zapata/primitive/var.rb:15:in `to_raw'
        from /Users/lun/.rvm/gems/ruby-2.0.0-p643/gems/zapata-0.1.5/lib/zapata/primitive/lvar.rb:16:in `to_raw'
        from /Users/lun/.rvm/gems/ruby-2.0.0-p643/gems/zapata-0.1.5/lib/zapata/primitive/send.rb:28:in `raw_receiver'
        from /Users/lun/.rvm/gems/ruby-2.0.0-p643/gems/zapata-0.1.5/lib/zapata/primitive/send.rb:32:in `to_raw'
        from /Users/lun/.rvm/gems/ruby-2.0.0-p643/gems/zapata-0.1.5/lib/zapata/primitive/send.rb:28:in `raw_receiver'
        from /Users/lun/.rvm/gems/ruby-2.0.0-p643/gems/zapata-0.1.5/lib/zapata/primitive/send.rb:32:in `to_raw'
        from /Users/lun/.rvm/gems/ruby-2.0.0-p643/gems/zapata-0.1.5/lib/zapata/primitive/send.rb:28:in `raw_receiver'
        from /Users/lun/.rvm/gems/ruby-2.0.0-p643/gems/zapata-0.1.5/lib/zapata/primitive/send.rb:32:in `to_raw'
        from /Users/lun/.rvm/gems/ruby-2.0.0-p643/gems/zapata-0.1.5/lib/zapata/primitive/send.rb:28:in `raw_receiver'
        from /Users/lun/.rvm/gems/ruby-2.0.0-p643/gems/zapata-0.1.5/lib/zapata/primitive/send.rb:32:in `to_raw'
        from /Users/lun/.rvm/gems/ruby-2.0.0-p643/gems/zapata-0.1.5/lib/zapata/primitive/var.rb:15:in `to_raw'
        from /Users/lun/.rvm/gems/ruby-2.0.0-p643/gems/zapata-0.1.5/lib/zapata/primitive/arg.rb:11:in `to_raw'
        from /Users/lun/.rvm/gems/ruby-2.0.0-p643/gems/zapata-0.1.5/lib/zapata/primitive/array.rb:17:in `block in to_raw'
        from /Users/lun/.rvm/gems/ruby-2.0.0-p643/gems/zapata-0.1.5/lib/zapata/primitive/array.rb:15:in `map'
        from /Users/lun/.rvm/gems/ruby-2.0.0-p643/gems/zapata-0.1.5/lib/zapata/primitive/array.rb:15:in `to_raw'
        from /Users/lun/.rvm/gems/ruby-2.0.0-p643/gems/zapata-0.1.5/lib/zapata/predictor/args.rb:8:in `literal'
        from /Users/lun/.rvm/gems/ruby-2.0.0-p643/gems/zapata-0.1.5/lib/zapata/primitive/def.rb:29:in `literal_predicted_args'
        from /Users/lun/.rvm/gems/ruby-2.0.0-p643/gems/zapata-0.1.5/lib/zapata/rzpec/writer.rb:100:in `write_method'
        from /Users/lun/.rvm/gems/ruby-2.0.0-p643/gems/zapata-0.1.5/lib/zapata/rzpec/writer.rb:55:in `block in write_class'
        from /Users/lun/.rvm/gems/ruby-2.0.0-p643/gems/zapata-0.1.5/lib/zapata/rzpec/writer.rb:54:in `each'
        from /Users/lun/.rvm/gems/ruby-2.0.0-p643/gems/zapata-0.1.5/lib/zapata/rzpec/writer.rb:54:in `write_class'
        from /Users/lun/.rvm/gems/ruby-2.0.0-p643/gems/zapata-0.1.5/lib/zapata/rzpec/writer.rb:23:in `block in initialize'
        from /Users/lun/.rvm/gems/ruby-2.0.0-p643/gems/zapata-0.1.5/lib/zapata/rzpec/writer.rb:22:in `each'
        from /Users/lun/.rvm/gems/ruby-2.0.0-p643/gems/zapata-0.1.5/lib/zapata/rzpec/writer.rb:22:in `initialize'
        from /Users/lun/.rvm/gems/ruby-2.0.0-p643/gems/zapata-0.1.5/lib/zapata.rb:84:in `new'
        from /Users/lun/.rvm/gems/ruby-2.0.0-p643/gems/zapata-0.1.5/lib/zapata.rb:84:in `generate_rspec_for'
        from /Users/lun/.rvm/gems/ruby-2.0.0-p643/gems/zapata-0.1.5/lib/zapata.rb:36:in `generate'
        from /Users/lun/.rvm/gems/ruby-2.0.0-p643/gems/zapata-0.1.5/lib/zapata.rb:28:in `generate_with_friendly_output'
        from /Users/lun/.rvm/gems/ruby-2.0.0-p643/gems/zapata-0.1.5/bin/zapata:20:in `block (3 levels) in <top (required)>'
        from /Users/lun/.rvm/gems/ruby-2.0.0-p643/gems/slop-3.6.0/lib/slop.rb:260:in `call'
        from /Users/lun/.rvm/gems/ruby-2.0.0-p643/gems/slop-3.6.0/lib/slop.rb:260:in `parse!'
        from /Users/lun/.rvm/gems/ruby-2.0.0-p643/gems/slop-3.6.0/lib/slop.rb:235:in `parse!'
        from /Users/lun/.rvm/gems/ruby-2.0.0-p643/gems/slop-3.6.0/lib/slop.rb:211:in `parse'
        from /Users/lun/.rvm/gems/ruby-2.0.0-p643/gems/zapata-0.1.5/bin/zapata:32:in `<top (required)>'
        from /Users/lun/.rvm/gems/ruby-2.0.0-p643/bin/zapata:23:in `load'
        from /Users/lun/.rvm/gems/ruby-2.0.0-p643/bin/zapata:23:in `<main>'
        from /Users/lun/.rvm/gems/ruby-2.0.0-p643/bin/ruby_executable_hooks:15:in `eval'
        from /Users/lun/.rvm/gems/ruby-2.0.0-p643/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by michaelachrisco** [comment]
What does the model look like?

**Comment by skatkov** [comment]
I've tried zapata on same project again and was unable to reproduce this error. Appears it was fixed (but project was not a stand still, so it might have been a project related issues that was fixed already).

**Comment by Nedomas** [comment]
Probably accidentally fixed. Reopen if anything.
