### ISSUE TITLE
Looks interesting - what's the status of this gem?

### ISSUE THREAD

**Issue by theirishpenguin** [Nedomas/zapata#20]
I am interested in using this gem. Is it obsolete?

In a simple model it generated a spec file for me but I got the error...

```
.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/json-2.1.0/lib/json/common.rb:156:in `parse': 765: unexpected token at 'Coverage report Rcov style generated for RSpec to /barg/foo/zoo_api/coverage/rcov (JSON::Pars
erError)
'
        from /home/bar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/json-2.1.0/lib/json/common.rb:156:in `parse'
        from /home/bar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/zapata-0.1.2/lib/zapata/rzpec/runner.rb:63:in `parsed_json_result'
        from /home/bar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/zapata-0.1.2/lib/zapata/rzpec/runner.rb:59:in `examples'
        from /home/bar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/zapata-0.1.2/lib/zapata/rzpec/runner.rb:26:in `methodz'
        from /home/bar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/zapata-0.1.2/lib/zapata/rzpec/runner.rb:30:in `result_message'
        from /home/bar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/zapata-0.1.2/lib/zapata/rzpec/runner.rb:34:in `expected'
        from /home/bar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/zapata-0.1.2/lib/zapata/rzpec/writer.rb:108:in `write_equal'
        from /home/bar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/zapata-0.1.2/lib/zapata/rzpec/writer.rb:100:in `write_method'
        from /home/bar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/zapata-0.1.2/lib/zapata/rzpec/writer.rb:55:in `block in write_class'
        from /home/bar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/zapata-0.1.2/lib/zapata/rzpec/writer.rb:54:in `each'
        from /home/bar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/zapata-0.1.2/lib/zapata/rzpec/writer.rb:54:in `write_class'
        from /home/bar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/zapata-0.1.2/lib/zapata/rzpec/writer.rb:23:in `block in initialize'
        from /home/bar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/zapata-0.1.2/lib/zapata/rzpec/writer.rb:22:in `each'
        from /home/bar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/zapata-0.1.2/lib/zapata/rzpec/writer.rb:22:in `initialize'
        from /home/bar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/zapata-0.1.2/lib/zapata.rb:83:in `new'
        from /home/bar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/zapata-0.1.2/lib/zapata.rb:83:in `generate_rspec_for'
        from /home/bar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/zapata-0.1.2/lib/zapata.rb:35:in `generate'
        from /home/bar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/zapata-0.1.2/lib/zapata.rb:27:in `generate_with_friendly_output'
        from /home/bar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/zapata-0.1.2/bin/zapata:20:in `block (3 levels) in <top (required)>'
        from /home/bar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/slop-3.6.0/lib/slop.rb:260:in `parse!'
        from /home/bar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/slop-3.6.0/lib/slop.rb:235:in `parse!'
        from /home/bar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/slop-3.6.0/lib/slop.rb:211:in `parse'
        from /home/bar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/zapata-0.1.2/bin/zapata:32:in `<top (required)>'
        from /home/bar/.rbenv/versions/2.3.1/bin/zapata:23:in `load'
        from /home/bar/.rbenv/versions/2.3.1/bin/zapata:23:in `<main>'

```

**Comment by Nedomas** [comment]
The new v1.0.0 was just released that support modern Ruby thanks to @marcinruszkiewicz #23 and @jpalumickas
